[package]
name = "scuisei-rs"
version = "0.1.1"
edition = "2024"
rust-version = "1.93.1"
description = "Scene-change detection library and CLI"
license = "MIT"
readme = "README.md"
repository = "https://github.com/yuv420p10le/scuisei-rs"
homepage = "https://github.com/yuv420p10le/scuisei-rs"
documentation = "https://docs.rs/scuisei-rs"
keywords = ["scene-detection", "video", "ffmpeg", "aegisub"]
categories = ["command-line-utilities", "multimedia::video"]
exclude = [
    ".github/**",
    ".devcontainer/**",
    ".venv/**",
    "dist/**",
]

[lib]
name = "scuisei_rs"
crate-type = ["rlib"]

[features]
default = []
python = ["dep:pyo3"]

[dependencies]
ffmpeg-next = { version = "=8.0.0", default-features = false, features = ["codec", "format", "software-scaling"] }
wide = "=1.1.1"
clap = { version = "=4.5.31", features = ["derive"] }
anyhow = "=1.0.95"
pyo3 = { version = "=0.23.5", optional = true, features = ["extension-module", "abi3-py39"] }
thiserror = "=2.0.11"

[dev-dependencies]
assert_cmd = "=2.0.16"
predicates = "=3.1.3"
proptest = "=1.6.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = 2
split-debuginfo = "off"
strip = "none"
